theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端开发工程师

# 对你自己的简洁描述
description: 现在是一个前端的初学者，勤勤恳恳，没有太大梦想，赚他一个亿就行。

# 你的美照地址
logo:/assets/images/me.jpg

# 你的名字
name:何文广（jerry.he）

# 你的联系方式
phone: 13590529292

# 你的邮箱
email: 904644871@qq.com

# 你目前的住址
address: 广东佛山

# 你毕业院校
school: 霍格沃茨学院

# 你的专业
profession: 电子信息工程

# 你的学位
degree: 学士学位

# 你获得过的证书或奖励
credential: 特别能吃奖
